"""add patient profile, insurance, hospitalization, diet, documents, emergency dispatch tables

Revision ID: 458b9caa59ac
Revises: ee3c44f04799
Create Date: 2026-09-01 11:05:20.923546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '458b9caa59ac'
down_revision: Union[str, Sequence[str], None] = 'ee3c44f04799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
