"""add latitude longitude to cases

Revision ID: 79ef78050b67
Revises: 8c1c7d4e9177
Create Date: 2026-09-01 12:36:07.925559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79ef78050b67'
down_revision: Union[str, Sequence[str], None] = '8c1c7d4e9177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('latitude', sa.String(), nullable=True))
    op.add_column('cases', sa.Column('longitude', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'longitude')
    op.drop_column('cases', 'latitude')
    # ### end Alembic commands ###
