"""add clinicians table

Revision ID: ee3c44f04799
Revises: 497aad4e2759
Create Date: 2026-08-24 16:22:41.485944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee3c44f04799'
down_revision: Union[str, Sequence[str], None] = '497aad4e2759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Clinicians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Clinicians_email'), 'Clinicians', ['email'], unique=True)
    op.create_index(op.f('ix_Clinicians_id'), 'Clinicians', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Clinicians_id'), table_name='Clinicians')
    op.drop_index(op.f('ix_Clinicians_email'), table_name='Clinicians')
    op.drop_table('Clinicians')
    # ### end Alembic commands ###
